#pragma config(Sensor, S1,     ,               sensorEV3_Color)
#pragma config(Sensor, S2,     ,               sensorEV3_Color)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Medium, openLoop, reversed, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Medium, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard      !!*//
	int err;
void goLine(int speed, float k){
	err = SensorValue[S1] - SensorValue[S2];
	Motor[motorB] = speed - (err*k);
	Motor[motorC] = speed + (err*k);
}

void linePer(int speed, float k, int per){
	int perNow=0;
	while(per < perNow)
	if(SensorValue[S1] < 32 && SensorValue[S2] <32){
		perNow++;
	}
	goline(speed, k);
}

task main(){
while ( true ){
//	displayCenteredTextLine(3, "Sensor Value: %d", SensorValue[S1]);

	//Wait 100 milliseconds to help display correctly
	//wait1Msec(100);

       //Erase the display
 //	eraseDisplay();
	linePer(50, 3, 1);
}
}
