#pragma config(Sensor, S1,     ,               sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     ,               sensorEV3_Color)
#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Medium, openLoop, reversed, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Medium, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int err, n, a;
int Color[10];
void goLine(int speed, float k){
	err = SensorValue[S3] - SensorValue[S2];
	motor[motorB] = speed - (err*k);
	motor[motorC] = speed + (err*k);
}

void linePer(int speed, float k, int per){
	int perNow=0;
	while(per > perNow){
		if(SensorValue[S3] < 32 && SensorValue[S2] < 32){
			perNow++;
		}
		goLine(speed, k);
	}
	motor[left] = 0;
	motor[right] = 0;
}

void povorot(char naw){
	if(naw == 'L'){
		goline(60,1.1);
		wait1Msec(70);
		motor[left] = -60;
		motor[right] = 60;
		wait1Msec(350);
		int sensorVal=0;
		while(SensorValue[S3] > 33){
			motor[left] = -40;
			motor[right] = 40;
		}
		motor[left] = STOP;
		motor[right] = STOP;
		}else if(naw == 'R'){
		goline(60,1.1);
		wait1Msec(70);
		motor[left] = 60;
		motor[right] = -60;
		wait1Msec(350);
		int sensorVal=0;
		while(SensorValue[S2] > 32){
			motor[left] = 40;
			motor[right] = -40;
		}
		motor[left] = STOP;
		motor[right] = STOP;

	}
}

task main(){
		n = 0;
		while (SensorValue[S3] > 32 || SensorValue[S2] > 32){
			goLine(60, 1.1);
			a = getMotorEncoder(motorC);
			if (getMotorEncoder(motorC)> n * 80 && n < 10){
				Color[n] = SensorValue[S1];
				if(SensorValue[S1] == 0) Color[n] = 3;
				else if(SensorValue[S1] == 2)Color[n]=1;
				else if(SensorValue[S1] == 4)Color[n]=0;
				else if(SensorValue[S1] == 5)Color[n]=2;
				n += 1;
			}
		}
		for (int i=0; i < 10; i++){
			displayTextLine(i + 1, "%d ", Color[i]);
		}
		motor[motorB] = 0;
		motor[motorC] = 0;
		wait1Msec(1000);

	for(int i = 0; i <=9; ++i){
		linePer(60, 1.3, 1);
		if(Color[i] == 0)povorot('L');
		else if(Color[i] == 1){
			povorot('R');
			goline(60,1.2);
			wait1Msec(200);
		}
		else if(Color[i] == 2){
			povorot('L');
			povorot('L');
		}else{
			goline(60,1.2);
			wait1Msec(200);
		}
		}
		linePer(60, 1.7, 1);
		wait1Msec(3000);
		goline(60, 1.7);
		wait1Msec(100);
		povorot('L');
		povorot('L');
	for(int k = 9; k >= 0; --k){
		linePer(60, 1.3, 1);
		if(Color[k] == 1)povorot('L');
		else if(Color[k] == 0){
			povorot('R');
			goline(60,1.2);
			wait1Msec(200);
		}
		else if(Color[k] == 2){
			povorot('L');
			povorot('L');
		}else{
			goline(60,1.2);
			wait1Msec(200);
		}
		}
		linePer(60, 1.7, 1);
		povorot('L');
		povorot('L');
		linePer(60, 1.7, 1);
		povorot('L');
		povorot('L');
		linePer(60, 1.7, 1);

}
