#pragma config(Sensor, S1,     ,               sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     ,               sensorEV3_Color)
#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Medium, openLoop, reversed, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Medium, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int err, n, a, y = 1, fin = 0;
int Color[6] = {0, 0, 0, 0, 0, 0};
void goLine(int speed, float k){
	err = SensorValue[S3] - SensorValue[S2];
	motor[motorB] = speed - (err*k);
	motor[motorC] = speed + (err*k);
}

void linePer(int speed, float k, int per){
	int perNow=0;
	while(per > perNow){
		if(SensorValue[S3] < 32 && SensorValue[S2] < 32){
			perNow++;
		}
		goLine(speed, k);
	}
	motor[left] = 0;
	motor[right] = 0;
	wait1Msec(300);
	if (y == 1){
		a = nMotorEncoder(motorC);
		while (nMotorEncoder(motorC) - a < 100){
				goLine(60, 1.1);
	  }
	  motor[left] = 0;
		motor[right] = 0;
		wait1Msec(300);
  }	
}

void povorot(char naw){
	if(naw == 'L'){
		motor[left] = -40;
		motor[right] = 40;
		wait1Msec(350);
		while(SensorValue[S3] > 33){
			motor[left] = -40;
			motor[right] = 40;
	}
	motor[left] = 0;
	motor[right] = 0;
	}
	else if(naw == 'R'){
		motor[left] = 40;
		motor[right] = -40;
		wait1Msec(350);
		while(SensorValue[S2] > 32){
			motor[left] = 40;
			motor[right] = -40;
		}
		motor[left] = 0;
		motor[right] = 0;

	}
}




task main(){
		while (SensorValue[S3] > 32 || SensorValue[S2] > 32){
			motor[left] = 30;
			motor[right] = 30;
		}
		a = nMotorEncoder(motorC);
		while (nMotorEncoder(motorC) - a < 90){
			goLine(30, 0.9);
	  }
	  n = 0;
		a = nMotorEncoder(motorC);
		while (SensorValue[S3] > 32 || SensorValue[S2] > 32){
			goLine(30, 0.9);
			if (nMotorEncoder(motorC) - a > n * 84.5 && n < 6){
				if(SensorValue[S1] != 0){
					Color[n] = 1;
			  }
				n += 1;
			}
		}
		a = nMotorEncoder(motorC);
		while (nMotorEncoder(motorC) - a < 100){
			goLine(30, 0.9);
		}
		for (int i=0; i < 6; i++){
			if (Color[i] == 0){
					continue;
			}
			else if (Color[i] == 1){
				if (i == 0){
					linePer(60, 1.1, 1);
					povorot('L');
					linePer(60, 1.1, 1);
					a = nMotorEncoder(motorC);
					while (nMotorEncoder(motorC) - a > -200){
							motor[motorB] = -30;
							motor[motorC] = -30;
				  }
				  povorot('R');
				  linePer(60, 1.1, 1);
				  povorot('R');
				  linePer(60, 1.1, 1);
				  linePer(60, 1.1, 1);
				  a = nMotorEncoder(motorC);
					while (nMotorEncoder(motorC) - a < 200){
							motor[motorB] = 30;
							motor[motorC] = 30;
				  }
					motor[motorB] = 0;
					motor[motorC] = 0;
				  delay(1500);
				  fin += 1;
				  if (fin != 3){
					  a = nMotorEncoder(motorC);
						while (nMotorEncoder(motorC) - a > -200){
								motor[motorB] = -30;
								motor[motorC] = -30;
					  }
					  povorot('R');
					  povorot('R');
					  linePer(60, 1.1, 1);
					}
				}
				else if (i == 1){
					linePer(60, 1.1, 1);
					linePer(60, 1.1, 1);
					a = nMotorEncoder(motorC);
					while (nMotorEncoder(motorC) - a > -200){
							motor[motorB] = -30;
							motor[motorC] = -30;
				  }
				  povorot('R');
				  linePer(60, 1.1, 1);
				  linePer(60, 1.1, 1);
				  linePer(60, 1.1, 1);
				  a = nMotorEncoder(motorC);
					while (nMotorEncoder(motorC) - a < 200){
							motor[motorB] = 30;
							motor[motorC] = 30;
				  }
					motor[motorB] = 0;
					motor[motorC] = 0;
				  delay(1500);
				  fin += 1;
				  if (fin != 3){
					  a = nMotorEncoder(motorC);
						while (nMotorEncoder(motorC) - a > -200){
								motor[motorB] = -30;
								motor[motorC] = -30;
					  }
					  povorot('R');
					  povorot('R');
					  linePer(60, 1.1, 1);
					}
				}
				else if (i == 2){
					povorot('R');
					linePer(60, 1.1, 1);
					linePer(60, 1.1, 1);
					povorot('R');
					linePer(60, 1.1, 1);
					povorot('L');
					linePer(60, 1.1, 1);
					a = nMotorEncoder(motorC);
					while (nMotorEncoder(motorC) - a > -200){
							motor[motorB] = -30;
							motor[motorC] = -30;
				  }
				  povorot('R');
				  linePer(60, 1.1, 1);
				  povorot('R');
				  linePer(60, 1.1, 1);
				  linePer(60, 1.1, 1);
				  povorot('R');
				  linePer(60, 1.1, 1);
				  povorot('L');
				  linePer(60, 1.1, 1);
				  a = nMotorEncoder(motorC);
					while (nMotorEncoder(motorC) - a < 200){
							motor[motorB] = 30;
							motor[motorC] = 30;
				  }
					motor[motorB] = 0;
					motor[motorC] = 0;
				  delay(1500);
				  fin += 1;
				  if (fin != 3){
					  a = nMotorEncoder(motorC);
						while (nMotorEncoder(motorC) - a > -200){
								motor[motorB] = -30;
								motor[motorC] = -30;
					  }
					  povorot('R');
					  povorot('R');
					  linePer(60, 1.1, 1);
					}
				}
				else if (i == 3){
					povorot('R');
					linePer(60, 1.1, 1);
					linePer(60, 1.1, 1);
					povorot('R');
					linePer(60, 1.1, 1);
					linePer(60, 1.1, 1);
					a = nMotorEncoder(motorC);
					while (nMotorEncoder(motorC) - a > -200){
							motor[motorB] = -30;
							motor[motorC] = -30;
				  }
				  povorot('R');
				  linePer(60, 1.1, 1);
				  linePer(60, 1.1, 1);
				  linePer(60, 1.1, 1);
				  povorot('R');
				  linePer(60, 1.1, 1);
				  povorot('L');
				  linePer(60, 1.1, 1);
				  a = nMotorEncoder(motorC);
					while (nMotorEncoder(motorC) - a < 200){
							motor[motorB] = 30;
							motor[motorC] = 30;
				  }
					motor[motorB] = 0;
					motor[motorC] = 0;
				  delay(1500);
				  fin += 1;
				  if (fin != 3){
					  a = nMotorEncoder(motorC);
						while (nMotorEncoder(motorC) - a > -200){
								motor[motorB] = -30;
								motor[motorC] = -30;
					  }
					  povorot('R');
					  povorot('R');
					  linePer(60, 1.1, 1);
					}
				}
				else if (i == 4){
										povorot('R');
					linePer(60, 1.1, 1);
					povorot('R');
					linePer(60, 1.1, 1);
					linePer(60, 1.1, 1);
					povorot('R');
					linePer(60, 1.1, 1);
					a = nMotorEncoder(motorC);
						while (nMotorEncoder(motorC) - a > -150){
								motor[motorB] = -30;
								motor[motorC] = -30;
					}
					povorot('R');
					linePer(60, 1.1, 1);
					povorot('L');
					linePer(60, 1.1, 1);
					linePer(60, 1.1, 1);
					povorot('L');
					linePer(60, 1.1, 1);
					povorot('L');
					linePer(60, 1.1, 1);
				  a = nMotorEncoder(motorC);
					while (nMotorEncoder(motorC) - a < 200){
							motor[motorB] = 30;
							motor[motorC] = 30;
				  }
					motor[motorB] = 0;
					motor[motorC] = 0;
				  delay(1500);
				  fin += 1;
				  if (fin != 3){
					  a = nMotorEncoder(motorC);
						while (nMotorEncoder(motorC) - a > -200){
								motor[motorB] = -30;
								motor[motorC] = -30;
					  }
					  povorot('R');
					  povorot('R');
					  linePer(60, 1.1, 1);
					}
				}
				else if (i == 5){
					povorot('R');
					linePer(60, 1.1, 1);
					povorot('R');
					linePer(60, 1.1, 1);
					povorot('R');
					linePer(60, 1.1, 1);
					a = nMotorEncoder(motorC);
						while (nMotorEncoder(motorC) - a > -150){
								motor[motorB] = -30;
								motor[motorC] = -30;
					}
					povorot('R');
					linePer(60, 1.1, 1);
					povorot('L');
					linePer(60, 1.1, 1);
					povorot('L');
					linePer(60, 1.1, 1);
					povorot('L');
					linePer(60, 1.1, 1);
				  a = nMotorEncoder(motorC);
					while (nMotorEncoder(motorC) - a < 200){
							motor[motorB] = 30;
							motor[motorC] = 30;
				  }
					motor[motorB] = 0;
					motor[motorC] = 0;
				  delay(1500);
				  fin += 1;
				  if (fin != 3){
					  a = nMotorEncoder(motorC);
						while (nMotorEncoder(motorC) - a > -200){
								motor[motorB] = -30;
								motor[motorC] = -30;
					  }
					  povorot('R');
					  povorot('R');
					  linePer(60, 1.1, 1);
					}
				}
		  }
		}
		motor[motorB] = 0;
		motor[motorC] = 0;

}
