#pragma config(Sensor, S1,     ,               sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     ,               sensorEV3_Color)
#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Medium, openLoop, reversed, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Medium, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int err, n, a, y = 1;
int Color[10];
void goLine(int speed, float k){
	err = SensorValue[S3] - SensorValue[S2];
	motor[motorB] = speed - (err*k);
	motor[motorC] = speed + (err*k);
}

void linePer(int speed, float k, int per){
	int perNow=0;
	while(per > perNow){
		if(SensorValue[S3] < 32 && SensorValue[S2] < 32){
			perNow++;
		}
		goLine(speed, k);
	}
	motor[left] = 0;
	motor[right] = 0;
	wait1Msec(300);
	if (y == 1){
		a = nMotorEncoder(motorC);
		while (nMotorEncoder(motorC) - a < 100){
				goLine(30, 0.9);
	  }
	  motor[left] = 0;
		motor[right] = 0;
		wait1Msec(300);
  }	
}

void povorot(char naw){
	if(naw == 'L'){
		motor[left] = -40;
		motor[right] = 40;
		wait1Msec(350);
		while(SensorValue[S3] > 33){
			motor[left] = -40;
			motor[right] = 40;
	}
	motor[left] = 0;
	motor[right] = 0;
	}
	else if(naw == 'R'){
		motor[left] = 40;
		motor[right] = -40;
		wait1Msec(350);
		while(SensorValue[S2] > 32){
			motor[left] = 40;
			motor[right] = -40;
		}
		motor[left] = 0;
		motor[right] = 0;

	}
}

task main(){
		while (SensorValue[S3] > 32 || SensorValue[S2] > 32){
			motor[left] = 30;
			motor[right] = 30;
		}
		a = nMotorEncoder(motorC);
		while (nMotorEncoder(motorC) - a < 90){
			goLine(30, 0.9);
	  }
	  motor[left] = 0;
		motor[right] = 0;
		wait1Msec(300);
		n = 0;
		a = nMotorEncoder(motorC);
		while (SensorValue[S3] > 32 || SensorValue[S2] > 32){
			goLine(30, 0.9);
			if (nMotorEncoder(motorC) - a > n * 84.5 && n < 10){
				if(SensorValue[S1] == 0) Color[n] = 3;
				else if(SensorValue[S1] == 2)Color[n]=1;
				else if(SensorValue[S1] == 4)Color[n]=0;
				else if(SensorValue[S1] == 5)Color[n]=2;
				n += 1;
			}
		}
		for (int i=0; i < 10; i++){
			displayTextLine(i + 1, "%d ", Color[i]);
		}
		motor[motorB] = 0;
		motor[motorC] = 0;
		wait1Msec(1000);

	for(int i = 0; i <=9; ++i){
		linePer(60, 0.7, 1);
		if(Color[i] == 0)povorot('L');
		else if(Color[i] == 1){
			povorot('R');
		}
		else if(Color[i] == 2){
			povorot('L');
			povorot('L');
		}
		}
		linePer(60, 0.7, 1);
		wait1Msec(1500);
		povorot('L');
		povorot('L');
	for(int k = 9; k >= 0; --k){
		linePer(60, 0.7, 1);
		if(Color[k] == 1)povorot('L');
		else if(Color[k] == 0){
			povorot('R');
		}
		else if(Color[k] == 2){
			povorot('L');
			povorot('L');
		}
	}
	y = 0;
	linePer(60, 0.7, 1);
	povorot('R');
	povorot('R');
	y = 0;
	linePer(60, 0.7, 1);
	povorot('R');
	povorot('R');
	y = 0;
	linePer(60, 0.7, 1);
	motor[left] = 40;
	motor[right] = 40;
	wait1Msec(800);
	motor[left] = 0;
	motor[right] = 0;

}
