#pragma config(Sensor, S1,     ,               sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     ,               sensorEV3_Color)
#pragma config(Sensor, S3,     ,               sensorEV3_Color)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Medium, openLoop, reversed, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Medium, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int err, n, a;
int Color[10];
void goLine(int speed, float k){
	err = SensorValue[S3] - SensorValue[S2];
	motor[motorB] = speed - (err*k);
	motor[motorC] = speed + (err*k);
}

void linePer(int speed, float k, int per){
	int perNow=0;
	while(per > perNow){
		if(SensorValue[S3] < 32 && SensorValue[S2] < 32){
			perNow++;
		}
		goLine(speed, k);
	}
	motor[left] = 0;
	motor[right] = 0;
}

void povorot(char naw){
	if(naw == 'L'){
		goline(60,1.1);
		wait1Msec(70);
		motor[left] = -60;
		motor[right] = 60;
		wait1Msec(350);
		int sensorVal=0;
		while(SensorValue[S3] > 33){
			motor[left] = -40;
			motor[right] = 40;
		}
		motor[left] = 0;
		motor[right] = 0;
		}else if(naw == 'R'){
		goline(60,1.1);
		wait1Msec(70);
		motor[left] = 60;
		motor[right] = -60;
		wait1Msec(350);
		int sensorVal=0;
		while(SensorValue[S2] > 32){
			motor[left] = 40;
			motor[right] = -40;
		}
		motor[left] = 0;
		motor[right] = 0;

	}
}

task main()
{
linePer(60, 1.1, 1);
if(abs(nMotorEncoder(left) - nMotorEncoder(right)) > 2000){
	playTone(10000, 50);
	wait1Msec(100);
}else{
 playTone(100, 50);
 wait1Msec(100);
}
	displayTextLine(3, "%d ", abs(nMotorEncoder(left) - nMotorEncoder(right)));
	wait1Msec(100000);
}
